name: 'base_cnn_v2' # It works for RGB images only (not MNIST)

# 'model'.pth filename
model_path: "base_cnn_v2.pth"
load_pretrained: False

# Training configs
num_epochs: 12
batch_size: 64
learning_rate: 0.01
optimizer: "sgd"